### ISSUE TITLE
HMR doesn't seem to be working. Full page reload.

### ISSUE THREAD

**Issue by empz** [psulek/react-mobx-react-router4-typescript-boilerplate#1]
I've cloned this repo, didn't make any modifications and when changing some text in a .tsx file, a full page refresh is being triggered.

Any ideas?

**Comment by psulek** [comment]
I see it refresh full page, but i think it is same as original repo (without ts). Or is this case only on this repo with typescript ?

**Comment by empz** [comment]
@psulek Yeah, I've just realized the original one does the same thing. Bummer.

**Comment by psulek** [comment]
@emzero But is this really a problem? This repo should show usage of typescript with mobx a stuff :-)

**Comment by psulek** [comment]
I will close this issue if you agree.

**Comment by zqgu2016** [comment]
@emzero I have the same problem, have you solved it yet?
